#!/usr/bin/env python3
"""Generate inline-SVG logo snippets for the theme from design-system/logos/.

Liquid can't render a snippet chosen by a variable, so snippets/gs-logo.liquid holds a
`case` over these generated files. Regenerate them whenever a logo SVG changes; never edit
the generated files by hand.

  python3 design-system/scripts/build_logo_snippets.py theme/snippets

Each generated snippet accepts one parameter, `label`:
  blank (default)  role="img" with the organisation's name as its accessible name
  'decorative'     aria-hidden, for a logo inside a link that already has a name (the header)
  any other text   used as the accessible name
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
# The logos the website uses (DESIGN.md §8.2). Add here, then add a `when` to gs-logo.liquid.
WEBSITE_LOGOS = [
    "gallery-simple-stacked-colour-box",
    "gallery-simple-horizontal-colour-box",
    "gallery-full-stacked-colour-box",
    "gallery-simple-stacked-white",
    "artists-for-kids-full-colour-box",
    "artists-for-kids-full-white",
    "foundation-simple-colour-box",
    "foundation-simple-white",
]

HEADER = (
    "{{%- comment -%}} Generated by design-system/scripts/build_logo_snippets.py from "
    "design-system/logos/{name}.svg. Do not edit. {{%- endcomment -%}}\n"
)
# No whitespace-control dashes here: they would glue this attribute to the one before it.
A11Y = (
    '{{% if label == "decorative" %}}aria-hidden="true" focusable="false"'
    '{{% else %}}role="img" aria-label="{{{{ label | default: "{alt}" | escape }}}}"{{% endif %}}'
)


def build(out_dir):
    manifest = json.loads((ROOT / "logos" / "logos.json").read_text())
    alt = {pathlib.Path(e["file"]).stem: e["altText"] for e in manifest["logos"]}
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name in WEBSITE_LOGOS:
        svg = (ROOT / "logos" / f"{name}.svg").read_text()
        svg = re.sub(r"<title>.*?</title>\s*", "", svg, flags=re.S)
        svg, n = re.subn(r'role="img" aria-label="[^"]*"', A11Y.format(alt=alt[name]), svg, count=1)
        if n != 1:
            raise SystemExit(f"{name}: expected one role/aria-label attribute")
        # Let CSS size the logo from its height; keep the viewBox for the aspect ratio.
        svg = re.sub(r'\swidth="[^"]*" height="[^"]*"', "", svg, count=1)
        svg = svg.replace("<svg ", f'<svg class="gs-logo gs-logo--{name}" ', 1)
        target = out_dir / f"gs-logo-{name}.liquid"
        target.write_text(HEADER.format(name=name) + svg.strip() + "\n")
        written.append(target)
    return written


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    for path in build(pathlib.Path(sys.argv[1])):
        print(path)
